### ISSUE TITLE
Paychecks gehen nicht 

### ISSUE THREAD

**Issue by Kamikatze1** [PC-Gamercom/pcg_tanoa#1]
Wioe ich euch schon in TS gesagt habe gehen die Paychacks noch nicht es wird dauerhaft durchgespammt "nächster Gehaltcheck in 5 minuten"
Hier eine fehlermeldung die damit zu tuen haben könnte 

waitUntil {vAH_loaded};
private["_total","_uid","_t>
23:03:13   Error position: <vAH_loaded};
private["_total","_uid","_t>
23:03:13   Error Nicht definierte Variable in Ausdruck: vah_loaded
23:03:13 File mpmissions__CUR_MP.TANOA\core\init.sqf, line 140
23:03:13 Error in expression <} else {
life_atmbank = life_atmbank + (call life_paycheck);
systemChat format[l>
23:03:13   Error position: <call life_paycheck);
systemChat format[l>
23:03:13   Error call: Typ Zahl, erwartet code
23:03:13 Error in expression <} else {
life_atmbank = life_atmbank + (call life_paycheck);
systemChat format[l>
23:03:13   Error position: <call life_paycheck);
systemChat format[l>
23:03:14   Error Allgemeiner Fehler in Ausdruck
23:03:14 Error in expression <2) closeDisplay 2; 
};
};

Dazu kommt noch das die respown auch niocht gehen den Fehler konnte ich auf die Mission SQM eingrenzen. Wehre echt nice wenn ich die fehler bald in griff bekommt.

LG Kami

**Comment by horrorpixel** [comment]
Hallo Kami es ist sehr nett das du mir eine Fehler meldung schickst aber
ich glaube du hast das an die falsche person geschickt.

LG Patrick S.

Am 22. Juli 2016 um 23:52 schrieb Kamikatze1 notifications@github.com:

**Comment by BigMikeOWL** [comment]
Hallo Kami,

ich schaue mir das ganze heute einmal an. Aktuell haben wir ein wenig viel zutun.
