### ISSUE TITLE
Problem mit der Garage

### ISSUE THREAD

**Issue by medaion** [PC-Gamercom/pcg_tanoa#2]
Guten Abend, ich habe ein Problem mit der Garage.
All mein Fahrzeug ich in der Garage war verschwunden.
Wie bitte dieses Problem an.

Sorry für mein schlechtes Allemend Ich bin französisch

**Comment by medaion** [comment]
Kann jemand mir helfen, mit der Garage bitte.
Ich benutze meine Garage Kern Ihnen nicht funktioniert

Sorry für meine allemend Ich bin Französisch

**Comment by shox92** [comment]
Pleaser write in English the Problem, I can´t speak France

**Comment by medaion** [comment]
I tried to reinstall your versions, but each time there as a mistake silk its garage that does not work, silk & I spawn the vendetta House prevent me from moving

**Comment by shox92** [comment]
Yes, that's still a bug that is resolved as soon as possible

**Comment by medaion** [comment]
Ok Thanks !

**Comment by medaion** [comment]
I found the solutions to garage bugs.
It's yours sql, it misses the impounds in I're added his walk now.
I was wondering if you told the added 3D view of the car shop.
I have a date I try I'm not successful ... if I find how I would send you.

As for the version she walks nikel has exceptions for house auctions.
Thank you for all the work you made for this version is really great
And sorry for English I use google translate

**Comment by GiJoe83** [comment]
Salut Medaion,
Tu pourrais me dire comment corriger le problème de garage s'il te plait ?
J'ai compris d’après les logs que c’était un problème de table je crois manquante...c'est çà ?
Sinon pour le respawn c'est normal que l'on ait une camera qui fait tout  buguer quand on meurt ?
Merci à toi ;-)

**Comment by GiJoe83** [comment]
hallo,
wie das Problem der Fahrzeuge zu lösen, die in der Garage nicht registrieren ?

**Comment by GiJoe83** [comment]
In English:

Hello,
how to solve the problem of vehicles that do not save in the garage ?
like say medaion

**Comment by medaion** [comment]
Bonsoir , désolé de pas avoir pus répondre avent , oui pour le garage ses un problème de table . 
Faut allé dans le msql & ajouté le Impound si non sa fonctionneras pas .

Ensuite pour la caméra j'ai pas bug moi , si tu parle des losage cela est normal .
C'est a toi de mettre ton intro a la mort si tu aime pas celle de base .

J'espère avoir pus t'aidé !

**Comment by GiJoe83** [comment]
Salut,
Merci d'avoir répondu, par contre si tu pouvais être un peu plus précis parceque tu as l'air d'avoir un très bon niveau mais moi pas autant lol.
Est ce que il manque une fonction dans le MySQL de la mission ? ou est ce que c'est dans la BDD qu'il manque un table ?

**Comment by medaion** [comment]
Salut , a vrais dit je suis au temps bon que toi .. si non moins .
Je suis aussi bon en développement que en français tu voie le genre XD
Je me débrouille un peux j'essaye d'apprendre donc je suis a la phase apprentis .

C'est dans la base de donnez mysql qui a un soucis , a la table véhicule . 
Regarde dedans il manque la variable impounds , j'ai vue cela quand j'ai regardé de plus pres dans le lifeserveur du côté de l'insersions a la base de donnez , j'ai vue qui avais l'envoie impound 
Et que dans la base msql il y avais pas ce mot la du coup je les rajouté & cela a fonctionnez .

**Comment by GiJoe83** [comment]
Ok d'acc, du coup je dois utiliser la console et ajouter une colonne si je comprend bien ?
La colonne impound ?
Je vais essayer parceque moi et la BDD ca fait deux mdr

**Comment by GiJoe83** [comment]
Je dois mettre quoi comme valeur dans "Name" "Type" "Lenght" "Decimals "Allow Null" ?
Dans name je suppose qu'il faut mettre : "impound"
Pour le reste je ne sais pas...

**Comment by medaion** [comment]
Voila ma table véhicule : 
 Nom      | TYPE | NULL |  DEFAULT |
impound |   int(1) | Non   |  0 |

**Comment by GiJoe83** [comment]
Super jte remercie jvais faire ca

**Comment by medaion** [comment]
Pas problème , la je dois partir mes si il y as quoi que ce soie mp moi .
Je répondrais des que possible !

**Comment by GiJoe83** [comment]
okay thanks

**Comment by GiJoe83** [comment]
tu me diras si c'est bon comme j'ai fait:

http://www.hostingpics.net/viewer.php?id=462890Sanstitre.png

**Comment by BigMikeOWL** [comment]
Sollte an und für sich behoben sein.
